# site metadata
description: A personal portfolio and blog for FL03
keywords: ["FL03", "portfolio", "blog", "personal", "developer", "programmer", "software engineer"]
lang: "en"
tagline: Portfolio of FL03
timezone: "America/Chicago"
title: FL03
# url configuration
baseurl: /
domain: fl03.github.io
url: https://fl03.github.io
# build configuration
destination: ./_site
source: ./src
# site settings
back_to_top: true
paginate: 10
theme: jekyll-theme-chirpy
# plugins
jekyll-spaceship:
  mermaid-processor:
    config:
      theme: default
mermaid:
  # Visit https://cdn.jsdelivr.net/npm/mermaid/ to find the latest version
  version: "11.7.0"
# biography
avatar             : "img/avatar.png"
social:
  name             : "Joe McCain III"
  email            : "j3mccai@gmail.com" 
  links:
    - "https://github.com/FL03"
    - "https://twitter.com/jo3mccain"
    - "https://orcid.org/0009-0003-3472-7523"
    - "https://www.linkedin.com/in/joe-mccain-iii/"

# social
github:
  username: FL03
twitter:
  username: jo3mccain

collections:
  posts:
    output: true
    sort_by: date  
    permalink: /:collection/:path/
  tabs:
    output: true
    sort_by: order
    permalink: /:collection/:path/

defaults:
  - scope:
      path: "" # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true # Enable comments in posts.
      toc: true # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs # see `site.collections`
    values:
      layout: page
      permalink: /:title/

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

assets:
  self_host:
    enabled: true

exclude:
  - README.md
  - LICENSE
  - .gitignore
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/